spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?useTimeZone=true&serverTimeZone=UTC
    username: postgres
    password: 100%Root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
